### ISSUE TITLE
it attempted to register ID Resourcekey

### ISSUE THREAD

**Issue by sparrow2323** [mircowuffwuff/create-diesel-generators-fabric-restitched#16]
attempted to register ID ResourceKey[minecraft:creative_mode_tab / minecraft:main] at different raw IDs (59, 78)! If you're trying to override an item, use .set(), not .register() is what it said when i checked the crash log

**Comment by mircowuffwuff** [comment]
are you sure that this is what crashed your game? either way, the full log would help
